class UserNotFoundError(Exception):
	"""Исключение, возникающее при попытке найти несуществующего пользователя."""
	pass